/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CastRouteImport } from './routes/cast'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemoteHostRouteImport } from './routes/remote.$host'
import { Route as PairHostRouteImport } from './routes/pair.$host'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CastRoute = CastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteHostRoute = RemoteHostRouteImport.update({
  id: '/remote/$host',
  path: '/remote/$host',
  getParentRoute: () => rootRouteImport,
} as any)
const PairHostRoute = PairHostRouteImport.update({
  id: '/pair/$host',
  path: '/pair/$host',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cast': typeof CastRoute
  '/settings': typeof SettingsRoute
  '/pair/$host': typeof PairHostRoute
  '/remote/$host': typeof RemoteHostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cast': typeof CastRoute
  '/settings': typeof SettingsRoute
  '/pair/$host': typeof PairHostRoute
  '/remote/$host': typeof RemoteHostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cast': typeof CastRoute
  '/settings': typeof SettingsRoute
  '/pair/$host': typeof PairHostRoute
  '/remote/$host': typeof RemoteHostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cast' | '/settings' | '/pair/$host' | '/remote/$host'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cast' | '/settings' | '/pair/$host' | '/remote/$host'
  id: '__root__' | '/' | '/cast' | '/settings' | '/pair/$host' | '/remote/$host'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CastRoute: typeof CastRoute
  SettingsRoute: typeof SettingsRoute
  PairHostRoute: typeof PairHostRoute
  RemoteHostRoute: typeof RemoteHostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cast': {
      id: '/cast'
      path: '/cast'
      fullPath: '/cast'
      preLoaderRoute: typeof CastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$host': {
      id: '/remote/$host'
      path: '/remote/$host'
      fullPath: '/remote/$host'
      preLoaderRoute: typeof RemoteHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair/$host': {
      id: '/pair/$host'
      path: '/pair/$host'
      fullPath: '/pair/$host'
      preLoaderRoute: typeof PairHostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CastRoute: CastRoute,
  SettingsRoute: SettingsRoute,
  PairHostRoute: PairHostRoute,
  RemoteHostRoute: RemoteHostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
